"""HSC syllabus structure mapped to Duolingo-style units and lessons.

Based on the NCTB (National Curriculum and Textbook Board) syllabus for
HSC Science stream, covering Physics, Chemistry, Math, and Biology.

Each subject is organized into Units (chapters) → Lessons (topics).
Lessons contain 5-15 exercises each.
"""

from __future__ import annotations

from .models import (
    Difficulty,
    Lesson,
    SubjectCurriculum,
    SubjectId,
    TargetExam,
    Unit,
)


def _lesson(
    id: str,
    title: str,
    title_bn: str,
    desc: str,
    desc_bn: str,
    difficulty: Difficulty = Difficulty.MEDIUM,
    order: int = 0,
    concepts: list[str] | None = None,
    prereqs: list[str] | None = None,
    minutes: int = 10,
) -> Lesson:
    return Lesson(
        id=id,
        title=title,
        title_bn=title_bn,
        description=desc,
        description_bn=desc_bn,
        difficulty=difficulty,
        order=order,
        concepts=concepts or [],
        prerequisites=prereqs or [],
        estimated_minutes=minutes,
    )


# ── PHYSICS ──────────────────────────────────────────────────────────────────

PHYSICS = SubjectCurriculum(
    subject=SubjectId.PHYSICS,
    title="Physics",
    title_bn="পদার্থবিজ্ঞান",
    icon="⚛️",
    target_exams=[TargetExam.BUET, TargetExam.DU, TargetExam.MEDICAL, TargetExam.GST],
    units=[
        Unit(
            id="phy-mechanics",
            title="Mechanics",
            title_bn="বলবিদ্যা",
            description="Motion, forces, energy, and momentum",
            description_bn="গতি, বল, শক্তি এবং ভরবেগ",
            icon="🚀",
            nctb_chapter="1-4",
            nctb_class="XI",
            order=1,
            lessons=[
                _lesson("phy-mech-01", "Physical Quantities & Units", "ভৌত রাশি ও একক",
                        "SI units, dimensions, measurement", "SI একক, মাত্রা, পরিমাপ",
                        Difficulty.EASY, 1, ["dimensional analysis", "SI units"]),
                _lesson("phy-mech-02", "Vectors", "ভেক্টর",
                        "Vector addition, resolution, dot & cross product",
                        "ভেক্টর যোগ, বিভাজন, ডট ও ক্রস গুণন",
                        Difficulty.MEDIUM, 2, ["vector components", "unit vector"]),
                _lesson("phy-mech-03", "Kinematics: 1D Motion", "সরলরৈখিক গতি",
                        "Equations of motion, free fall, velocity-time graphs",
                        "গতির সমীকরণ, মুক্ত পতন, বেগ-সময় লেখচিত্র",
                        Difficulty.EASY, 3, ["v=u+at", "s=ut+½at²"], minutes=15),
                _lesson("phy-mech-04", "Kinematics: 2D & Projectile", "প্রক্ষেপ গতি",
                        "Projectile motion, range, max height, time of flight",
                        "প্রক্ষেপ গতি, পাল্লা, সর্বোচ্চ উচ্চতা",
                        Difficulty.MEDIUM, 4, ["projectile", "range formula"],
                        prereqs=["phy-mech-03"]),
                _lesson("phy-mech-05", "Newton's Laws", "নিউটনের সূত্রসমূহ",
                        "Three laws of motion, friction, FBD",
                        "গতির তিনটি সূত্র, ঘর্ষণ, মুক্তবস্তু চিত্র",
                        Difficulty.MEDIUM, 5, ["F=ma", "friction", "FBD"], minutes=15),
                _lesson("phy-mech-06", "Work, Energy & Power", "কাজ, শক্তি ও ক্ষমতা",
                        "Work-energy theorem, KE, PE, conservation",
                        "কাজ-শক্তি উপপাদ্য, গতিশক্তি, বিভবশক্তি",
                        Difficulty.MEDIUM, 6, ["W=Fd", "KE=½mv²"]),
                _lesson("phy-mech-07", "Momentum & Collisions", "ভরবেগ ও সংঘর্ষ",
                        "Conservation of momentum, elastic/inelastic collisions",
                        "ভরবেগের সংরক্ষণ, স্থিতিস্থাপক/অস্থিতিস্থাপক সংঘর্ষ",
                        Difficulty.HARD, 7, ["p=mv", "impulse"]),
                _lesson("phy-mech-08", "Rotational Motion", "ঘূর্ণন গতি",
                        "Torque, angular momentum, moment of inertia",
                        "টর্ক, কৌণিক ভরবেগ, জড়তার ভ্রামক",
                        Difficulty.HARD, 8, ["τ=Iα", "L=Iω"], minutes=15),
            ],
        ),
        Unit(
            id="phy-waves",
            title="Waves & Oscillations",
            title_bn="তরঙ্গ ও স্পন্দন",
            description="SHM, wave properties, sound, light",
            description_bn="সরল ছন্দিত গতি, তরঙ্গ, শব্দ, আলো",
            icon="🌊",
            nctb_chapter="5-7",
            nctb_class="XI",
            order=2,
            lessons=[
                _lesson("phy-wave-01", "Simple Harmonic Motion", "সরল ছন্দিত গতি",
                        "SHM equation, period, amplitude, energy",
                        "SHM সমীকরণ, পর্যায়কাল, বিস্তার, শক্তি",
                        Difficulty.MEDIUM, 1, ["x=Asin(ωt)", "T=2π/ω"]),
                _lesson("phy-wave-02", "Wave Properties", "তরঙ্গের বৈশিষ্ট্য",
                        "Wavelength, frequency, speed, transverse & longitudinal",
                        "তরঙ্গদৈর্ঘ্য, কম্পাঙ্ক, বেগ, অনুপ্রস্থ ও অনুদৈর্ঘ্য",
                        Difficulty.EASY, 2, ["v=fλ"]),
                _lesson("phy-wave-03", "Sound Waves", "শব্দ তরঙ্গ",
                        "Doppler effect, resonance, beats",
                        "ডপলার ক্রিয়া, অনুনাদ, বীট",
                        Difficulty.MEDIUM, 3, ["doppler", "beats"]),
                _lesson("phy-wave-04", "Light: Reflection & Refraction", "আলো: প্রতিফলন ও প্রতিসরণ",
                        "Snell's law, total internal reflection, lenses",
                        "স্নেলের সূত্র, পূর্ণ অভ্যন্তরীণ প্রতিফলন, লেন্স",
                        Difficulty.MEDIUM, 4, ["n₁sinθ₁=n₂sinθ₂"]),
                _lesson("phy-wave-05", "Interference & Diffraction", "ব্যতিচার ও অপবর্তন",
                        "Young's double slit, single slit diffraction",
                        "ইয়ংয়ের দ্বি-চির পরীক্ষা, একক চির অপবর্তন",
                        Difficulty.HARD, 5, ["path difference", "fringe width"]),
            ],
        ),
        Unit(
            id="phy-electricity",
            title="Electricity & Magnetism",
            title_bn="তড়িৎ ও চুম্বকত্ব",
            description="Electrostatics, circuits, electromagnetic induction",
            description_bn="স্থিরতড়িৎ, বর্তনী, তড়িৎচুম্বকীয় আবেশ",
            icon="⚡",
            nctb_chapter="8-12",
            nctb_class="XII",
            order=3,
            lessons=[
                _lesson("phy-elec-01", "Coulomb's Law & Electric Field", "কুলম্বের সূত্র ও তড়িৎ ক্ষেত্র",
                        "Point charges, field lines, superposition",
                        "বিন্দু চার্জ, ক্ষেত্র রেখা, উপরিপাতন",
                        Difficulty.MEDIUM, 1, ["F=kq₁q₂/r²", "E=F/q"]),
                _lesson("phy-elec-02", "Electric Potential & Capacitance", "তড়িৎ বিভব ও ধারকত্ব",
                        "Potential, potential energy, capacitors",
                        "বিভব, বিভবশক্তি, ধারক",
                        Difficulty.MEDIUM, 2, ["V=kq/r", "C=Q/V"]),
                _lesson("phy-elec-03", "DC Circuits", "সমবর্তনী",
                        "Ohm's law, Kirchhoff's rules, series/parallel",
                        "ওহমের সূত্র, কির্শফের সূত্র, শ্রেণী/সমান্তরাল",
                        Difficulty.MEDIUM, 3, ["V=IR", "Kirchhoff"], minutes=15),
                _lesson("phy-elec-04", "Magnetic Fields", "চুম্বক ক্ষেত্র",
                        "Biot-Savart, Ampere's law, Lorentz force",
                        "বায়ো-স্যাভার্ট, অ্যাম্পিয়ারের সূত্র, লরেঞ্জ বল",
                        Difficulty.HARD, 4, ["F=qvB", "Ampere"]),
                _lesson("phy-elec-05", "Electromagnetic Induction", "তড়িৎচুম্বকীয় আবেশ",
                        "Faraday's law, Lenz's law, AC generator",
                        "ফ্যারাডের সূত্র, লেঞ্জের সূত্র, AC জেনারেটর",
                        Difficulty.HARD, 5, ["emf=-dΦ/dt"]),
            ],
        ),
        Unit(
            id="phy-modern",
            title="Modern Physics",
            title_bn="আধুনিক পদার্থবিজ্ঞান",
            description="Quantum physics, atomic structure, nuclear physics",
            description_bn="কোয়ান্টাম পদার্থবিজ্ঞান, পরমাণু গঠন, নিউক্লীয় পদার্থবিজ্ঞান",
            icon="🔬",
            nctb_chapter="13-14",
            nctb_class="XII",
            order=4,
            lessons=[
                _lesson("phy-mod-01", "Photoelectric Effect", "আলোক তড়িৎ ক্রিয়া",
                        "Einstein's equation, work function, threshold frequency",
                        "আইনস্টাইনের সমীকরণ, কার্যঅপেক্ষক, প্রান্তিক কম্পাঙ্ক",
                        Difficulty.MEDIUM, 1, ["E=hf", "KE=hf-φ"]),
                _lesson("phy-mod-02", "Atomic Models", "পরমাণু মডেল",
                        "Bohr model, energy levels, hydrogen spectrum",
                        "বোর মডেল, শক্তিস্তর, হাইড্রোজেন বর্ণালী",
                        Difficulty.MEDIUM, 2, ["Bohr model", "energy levels"]),
                _lesson("phy-mod-03", "Nuclear Physics", "নিউক্লীয় পদার্থবিজ্ঞান",
                        "Radioactivity, decay, fission, fusion, E=mc²",
                        "তেজস্ক্রিয়তা, ক্ষয়, বিভাজন, সংযোজন",
                        Difficulty.HARD, 3, ["E=mc²", "half-life"]),
                _lesson("phy-mod-04", "Semiconductors", "অর্ধপরিবাহী",
                        "p-n junction, diodes, transistors",
                        "p-n সংযোগ, ডায়োড, ট্রানজিস্টর",
                        Difficulty.MEDIUM, 4, ["p-n junction", "LED"]),
            ],
        ),
    ],
)


# ── CHEMISTRY ────────────────────────────────────────────────────────────────

CHEMISTRY = SubjectCurriculum(
    subject=SubjectId.CHEMISTRY,
    title="Chemistry",
    title_bn="রসায়ন",
    icon="⚗️",
    target_exams=[TargetExam.BUET, TargetExam.DU, TargetExam.MEDICAL, TargetExam.GST],
    units=[
        Unit(
            id="chem-structure",
            title="Atomic Structure & Chemical Bonding",
            title_bn="পরমাণুর গঠন ও রাসায়নিক বন্ধন",
            description="Electron configuration, periodic table, bonds",
            description_bn="ইলেকট্রন বিন্যাস, পর্যায় সারণী, বন্ধন",
            icon="🔮",
            nctb_chapter="1-3",
            nctb_class="XI",
            order=1,
            lessons=[
                _lesson("chem-str-01", "Atomic Structure", "পরমাণুর গঠন",
                        "Quantum numbers, electron configuration, orbitals",
                        "কোয়ান্টাম সংখ্যা, ইলেকট্রন বিন্যাস, অরবিটাল",
                        Difficulty.MEDIUM, 1, ["quantum numbers", "aufbau"]),
                _lesson("chem-str-02", "Periodic Table", "পর্যায় সারণী",
                        "Trends, groups, periods, properties",
                        "প্রবণতা, গ্রুপ, পর্যায়, ধর্ম",
                        Difficulty.EASY, 2, ["periodic trends", "electronegativity"]),
                _lesson("chem-str-03", "Chemical Bonding", "রাসায়নিক বন্ধন",
                        "Ionic, covalent, metallic, hydrogen bonding",
                        "আয়নিক, সমযোজী, ধাতব, হাইড্রোজেন বন্ধন",
                        Difficulty.MEDIUM, 3, ["ionic bond", "covalent bond", "VSEPR"]),
            ],
        ),
        Unit(
            id="chem-physical",
            title="Physical Chemistry",
            title_bn="ভৌত রসায়ন",
            description="States of matter, thermodynamics, equilibrium, electrochemistry",
            description_bn="পদার্থের অবস্থা, তাপগতিবিদ্যা, সাম্যাবস্থা, তড়িৎরসায়ন",
            icon="🌡️",
            nctb_chapter="4-7",
            nctb_class="XI-XII",
            order=2,
            lessons=[
                _lesson("chem-phy-01", "States of Matter & Gas Laws", "পদার্থের অবস্থা ও গ্যাস সূত্র",
                        "Ideal gas, Boyle's, Charles', kinetic theory",
                        "আদর্শ গ্যাস, বয়েলের সূত্র, চার্লসের সূত্র",
                        Difficulty.EASY, 1, ["PV=nRT"]),
                _lesson("chem-phy-02", "Thermochemistry", "তাপরসায়ন",
                        "Enthalpy, Hess's law, bond energy",
                        "এনথালপি, হেসের সূত্র, বন্ধন শক্তি",
                        Difficulty.MEDIUM, 2, ["ΔH", "Hess's law"]),
                _lesson("chem-phy-03", "Chemical Equilibrium", "রাসায়নিক সাম্যাবস্থা",
                        "Kp, Kc, Le Chatelier's principle",
                        "Kp, Kc, লা শাতেলিয়ের নীতি",
                        Difficulty.MEDIUM, 3, ["K_eq", "Le Chatelier"]),
                _lesson("chem-phy-04", "Acids, Bases & pH", "অম্ল, ক্ষার ও pH",
                        "pH scale, buffers, titration, indicators",
                        "pH স্কেল, বাফার, টাইট্রেশন, নির্দেশক",
                        Difficulty.MEDIUM, 4, ["pH=-log[H+]"]),
                _lesson("chem-phy-05", "Electrochemistry", "তড়িৎরসায়ন",
                        "Redox, electrochemical cells, Nernst equation",
                        "রেডক্স, তড়িৎরাসায়নিক কোষ, নার্ন্স্ট সমীকরণ",
                        Difficulty.HARD, 5, ["E°cell", "Nernst"]),
            ],
        ),
        Unit(
            id="chem-organic",
            title="Organic Chemistry",
            title_bn="জৈব রসায়ন",
            description="Hydrocarbons, functional groups, reactions, naming",
            description_bn="হাইড্রোকার্বন, কার্যকরী গ্রুপ, বিক্রিয়া, নামকরণ",
            icon="🧪",
            nctb_chapter="8-11",
            nctb_class="XII",
            order=3,
            lessons=[
                _lesson("chem-org-01", "IUPAC Naming", "IUPAC নামকরণ",
                        "Naming alkanes, alkenes, alkynes, functional groups",
                        "অ্যালকেন, অ্যালকিন, অ্যালকাইন ও কার্যকরী গ্রুপের নামকরণ",
                        Difficulty.MEDIUM, 1, ["IUPAC rules", "prefix/suffix"]),
                _lesson("chem-org-02", "Hydrocarbons", "হাইড্রোকার্বন",
                        "Alkanes, alkenes, alkynes, aromatic compounds",
                        "অ্যালকেন, অ্যালকিন, অ্যালকাইন, অ্যারোমাটিক যৌগ",
                        Difficulty.MEDIUM, 2, ["isomerism", "hybridization"]),
                _lesson("chem-org-03", "Alcohols & Ethers", "অ্যালকোহল ও ইথার",
                        "Properties, reactions, preparation",
                        "ধর্ম, বিক্রিয়া, প্রস্তুতি",
                        Difficulty.MEDIUM, 3, ["OH group", "dehydration"]),
                _lesson("chem-org-04", "Aldehydes & Ketones", "অ্যালডিহাইড ও কিটোন",
                        "Carbonyl group, nucleophilic addition, tests",
                        "কার্বনিল গ্রুপ, নিউক্লিওফিলিক সংযোজন, পরীক্ষা",
                        Difficulty.HARD, 4, ["carbonyl", "Tollens test"]),
                _lesson("chem-org-05", "Carboxylic Acids & Derivatives", "কার্বক্সিলিক এসিড",
                        "Acids, esters, amides, acyl chlorides",
                        "এসিড, এস্টার, অ্যামাইড, অ্যাসিল ক্লোরাইড",
                        Difficulty.HARD, 5, ["COOH", "esterification"]),
                _lesson("chem-org-06", "Polymers & Biomolecules", "পলিমার ও জৈব অণু",
                        "Polymerization, proteins, carbohydrates, fats",
                        "পলিমারকরণ, প্রোটিন, শর্করা, চর্বি",
                        Difficulty.MEDIUM, 6, ["addition polymer", "condensation"]),
            ],
        ),
        Unit(
            id="chem-inorganic",
            title="Inorganic Chemistry",
            title_bn="অজৈব রসায়ন",
            description="Transition metals, coordination compounds, qualitative analysis",
            description_bn="অবস্থান্তর ধাতু, সন্নিবেশ যৌগ, গুণগত বিশ্লেষণ",
            icon="💎",
            nctb_chapter="12-14",
            nctb_class="XII",
            order=4,
            lessons=[
                _lesson("chem-inorg-01", "s-block & p-block Elements", "s-ব্লক ও p-ব্লক মৌল",
                        "Properties of alkali metals, halogens, noble gases",
                        "ক্ষার ধাতু, হ্যালোজেন, নিষ্ক্রিয় গ্যাসের ধর্ম",
                        Difficulty.EASY, 1, ["group trends"]),
                _lesson("chem-inorg-02", "d-block Elements", "d-ব্লক মৌল",
                        "Transition metals, oxidation states, color",
                        "অবস্থান্তর ধাতু, জারণ অবস্থা, বর্ণ",
                        Difficulty.MEDIUM, 2, ["variable oxidation", "catalysts"]),
                _lesson("chem-inorg-03", "Coordination Chemistry", "সন্নিবেশ রসায়ন",
                        "Ligands, coordination number, isomerism",
                        "লিগ্যান্ড, সন্নিবেশ সংখ্যা, সমাণুতা",
                        Difficulty.HARD, 3, ["Werner theory", "crystal field"]),
            ],
        ),
    ],
)


# ── HIGHER MATH ──────────────────────────────────────────────────────────────

HIGHER_MATH = SubjectCurriculum(
    subject=SubjectId.HIGHER_MATH,
    title="Higher Mathematics",
    title_bn="উচ্চতর গণিত",
    icon="📐",
    target_exams=[TargetExam.BUET, TargetExam.DU, TargetExam.GST],
    units=[
        Unit(
            id="hmath-calculus",
            title="Calculus",
            title_bn="ক্যালকুলাস",
            description="Differentiation, integration, limits, applications",
            description_bn="অন্তরকলন, সমাকলন, সীমা, প্রয়োগ",
            icon="∫",
            nctb_chapter="1-4",
            nctb_class="XII",
            order=1,
            lessons=[
                _lesson("hm-calc-01", "Limits & Continuity", "সীমা ও সন্ততা",
                        "Limits, L'Hôpital's rule, continuity",
                        "সীমা, ল'হপিতালের সূত্র, সন্ততা",
                        Difficulty.MEDIUM, 1, ["limit definition", "L'Hôpital"]),
                _lesson("hm-calc-02", "Differentiation Rules", "অন্তরকলনের নিয়ম",
                        "Power, product, quotient, chain rule",
                        "ঘাত, গুণন, ভাগ, শৃঙ্খল নিয়ম",
                        Difficulty.MEDIUM, 2, ["chain rule", "product rule"]),
                _lesson("hm-calc-03", "Applications of Derivatives", "অন্তরকলনের প্রয়োগ",
                        "Maxima/minima, rate of change, curve sketching",
                        "চরম/অবম মান, পরিবর্তনের হার",
                        Difficulty.HARD, 3, ["optimization", "related rates"]),
                _lesson("hm-calc-04", "Integration Basics", "সমাকলনের মূলনীতি",
                        "Indefinite integrals, basic rules, substitution",
                        "অনির্দিষ্ট সমাকলন, মূল নিয়ম, প্রতিস্থাপন",
                        Difficulty.MEDIUM, 4, ["∫xⁿdx", "substitution"]),
                _lesson("hm-calc-05", "Definite Integrals & Applications", "নির্দিষ্ট সমাকলন ও প্রয়োগ",
                        "Area under curve, volume of revolution",
                        "বক্ররেখার নিচের ক্ষেত্রফল, ঘূর্ণনের আয়তন",
                        Difficulty.HARD, 5, ["area", "volume"]),
            ],
        ),
        Unit(
            id="hmath-algebra",
            title="Algebra",
            title_bn="বীজগণিত",
            description="Complex numbers, matrices, determinants, sequences",
            description_bn="জটিল সংখ্যা, ম্যাট্রিক্স, নির্ণায়ক, ধারা",
            icon="🔢",
            nctb_chapter="5-8",
            nctb_class="XI",
            order=2,
            lessons=[
                _lesson("hm-alg-01", "Complex Numbers", "জটিল সংখ্যা",
                        "Argand diagram, polar form, De Moivre's theorem",
                        "আর্গান্ড চিত্র, পোলার রূপ, দ্য ময়ভ্রের উপপাদ্য",
                        Difficulty.MEDIUM, 1, ["i²=-1", "modulus"]),
                _lesson("hm-alg-02", "Matrices & Determinants", "ম্যাট্রিক্স ও নির্ণায়ক",
                        "Matrix operations, inverse, Cramer's rule",
                        "ম্যাট্রিক্স ক্রিয়া, বিপরীত, ক্র্যামারের সূত্র",
                        Difficulty.MEDIUM, 2, ["det(A)", "inverse"]),
                _lesson("hm-alg-03", "Sequences & Series", "ধারা ও শ্রেণী",
                        "AP, GP, binomial theorem, summation",
                        "সমান্তর ধারা, গুণোত্তর ধারা, দ্বিপদ উপপাদ্য",
                        Difficulty.MEDIUM, 3, ["AP", "GP", "binomial"]),
                _lesson("hm-alg-04", "Logarithms & Exponentials", "লগারিদম ও সূচক",
                        "Log rules, change of base, exponential equations",
                        "লগের নিয়ম, ভিত্তি পরিবর্তন, সূচকীয় সমীকরণ",
                        Difficulty.EASY, 4, ["log rules"]),
            ],
        ),
        Unit(
            id="hmath-trig",
            title="Trigonometry",
            title_bn="ত্রিকোণমিতি",
            description="Identities, equations, inverse functions, applications",
            description_bn="অভেদ, সমীকরণ, বিপরীত ফাংশন, প্রয়োগ",
            icon="📏",
            nctb_chapter="9-10",
            nctb_class="XI",
            order=3,
            lessons=[
                _lesson("hm-trig-01", "Trigonometric Identities", "ত্রিকোণমিতিক অভেদ",
                        "Fundamental identities, compound angles",
                        "মৌলিক অভেদ, যৌগিক কোণ",
                        Difficulty.MEDIUM, 1, ["sin²+cos²=1", "compound angle"]),
                _lesson("hm-trig-02", "Trigonometric Equations", "ত্রিকোণমিতিক সমীকরণ",
                        "General solutions, quadrant rules",
                        "সাধারণ সমাধান, পাদ নিয়ম",
                        Difficulty.HARD, 2, ["general solution"]),
                _lesson("hm-trig-03", "Inverse Trigonometry", "বিপরীত ত্রিকোণমিতি",
                        "sin⁻¹, cos⁻¹, tan⁻¹, properties",
                        "sin⁻¹, cos⁻¹, tan⁻¹, ধর্ম",
                        Difficulty.HARD, 3, ["principal value"]),
            ],
        ),
        Unit(
            id="hmath-coord",
            title="Coordinate Geometry",
            title_bn="স্থানাঙ্ক জ্যামিতি",
            description="Straight lines, circles, conics, 3D geometry",
            description_bn="সরলরেখা, বৃত্ত, কনিক, ত্রিমাত্রিক জ্যামিতি",
            icon="📊",
            nctb_chapter="11-13",
            nctb_class="XI-XII",
            order=4,
            lessons=[
                _lesson("hm-coord-01", "Straight Lines", "সরলরেখা",
                        "Slope, equations, distance, angle between lines",
                        "ঢাল, সমীকরণ, দূরত্ব, রেখাদ্বয়ের মধ্যবর্তী কোণ",
                        Difficulty.EASY, 1, ["y=mx+c"]),
                _lesson("hm-coord-02", "Circles", "বৃত্ত",
                        "Equation, tangent, normal, intersection",
                        "সমীকরণ, স্পর্শক, অভিলম্ব, ছেদ",
                        Difficulty.MEDIUM, 2, ["x²+y²=r²"]),
                _lesson("hm-coord-03", "Conic Sections", "কনিক",
                        "Parabola, ellipse, hyperbola",
                        "পরাবৃত্ত, উপবৃত্ত, অধিবৃত্ত",
                        Difficulty.HARD, 3, ["e<1 ellipse", "e>1 hyperbola"]),
            ],
        ),
    ],
)


# ── GENERAL MATH ─────────────────────────────────────────────────────────────

GENERAL_MATH = SubjectCurriculum(
    subject=SubjectId.GENERAL_MATH,
    title="General Mathematics",
    title_bn="সাধারণ গণিত",
    icon="➕",
    target_exams=[TargetExam.DU, TargetExam.MEDICAL, TargetExam.GST],
    units=[
        Unit(
            id="gmath-arithmetic",
            title="Arithmetic & Number Theory",
            title_bn="পাটিগণিত ও সংখ্যাতত্ত্ব",
            description="Ratio, percentage, profit-loss, LCM/HCF, divisibility",
            description_bn="অনুপাত, শতকরা, লাভ-ক্ষতি, লসাগু/গসাগু, বিভাজ্যতা",
            icon="🔢",
            order=1,
            lessons=[
                _lesson("gm-arith-01", "Ratio & Proportion", "অনুপাত ও সমানুপাত",
                        "Simple, compound ratios, proportional division",
                        "সরল, যৌগিক অনুপাত, সমানুপাতিক ভাগ",
                        Difficulty.EASY, 1),
                _lesson("gm-arith-02", "Percentage & Profit-Loss", "শতকরা ও লাভ-ক্ষতি",
                        "Percentage, discount, markup, successive changes",
                        "শতকরা, ছাড়, মূল্য বৃদ্ধি, ক্রমিক পরিবর্তন",
                        Difficulty.EASY, 2),
                _lesson("gm-arith-03", "Time, Speed & Distance", "সময়, বেগ ও দূরত্ব",
                        "Average speed, relative motion, trains/boats",
                        "গড় বেগ, আপেক্ষিক গতি, ট্রেন/নৌকা",
                        Difficulty.MEDIUM, 3),
            ],
        ),
        Unit(
            id="gmath-algebra-basic",
            title="Basic Algebra",
            title_bn="মৌলিক বীজগণিত",
            description="Equations, inequalities, functions, polynomials",
            description_bn="সমীকরণ, অসমতা, ফাংশন, বহুপদী",
            icon="🅰️",
            order=2,
            lessons=[
                _lesson("gm-alg-01", "Linear Equations", "সরল সমীকরণ",
                        "Solving, word problems, simultaneous equations",
                        "সমাধান, ব্যবহারিক সমস্যা, যুগপৎ সমীকরণ",
                        Difficulty.EASY, 1),
                _lesson("gm-alg-02", "Quadratic Equations", "দ্বিঘাত সমীকরণ",
                        "Factoring, formula, discriminant, nature of roots",
                        "উৎপাদকে বিশ্লেষণ, সূত্র, নির্ণায়ক, মূলের প্রকৃতি",
                        Difficulty.MEDIUM, 2, ["b²-4ac"]),
                _lesson("gm-alg-03", "Sets & Functions", "সেট ও ফাংশন",
                        "Venn diagrams, domain, range, composition",
                        "ভেন চিত্র, ডোমেইন, রেঞ্জ, যৌগিক ফাংশন",
                        Difficulty.MEDIUM, 3),
            ],
        ),
        Unit(
            id="gmath-stats",
            title="Statistics & Probability",
            title_bn="পরিসংখ্যান ও সম্ভাব্যতা",
            description="Mean, median, mode, probability, permutations",
            description_bn="গড়, মধ্যমা, প্রচুরক, সম্ভাব্যতা, বিন্যাস",
            icon="📈",
            order=3,
            lessons=[
                _lesson("gm-stat-01", "Measures of Central Tendency", "কেন্দ্রীয় প্রবণতার পরিমাপ",
                        "Mean, median, mode for grouped/ungrouped data",
                        "গড়, মধ্যমা, প্রচুরক",
                        Difficulty.EASY, 1),
                _lesson("gm-stat-02", "Probability", "সম্ভাব্যতা",
                        "Basic, conditional, Bayes theorem, independent events",
                        "মৌলিক, শর্তাধীন, বেইজ উপপাদ্য",
                        Difficulty.MEDIUM, 2, ["P(A∩B)", "Bayes"]),
                _lesson("gm-stat-03", "Permutations & Combinations", "বিন্যাস ও সমাবেশ",
                        "nPr, nCr, applications",
                        "nPr, nCr, প্রয়োগ",
                        Difficulty.MEDIUM, 3, ["nCr=n!/(r!(n-r)!)"]),
            ],
        ),
    ],
)


# ── BIOLOGY ──────────────────────────────────────────────────────────────────

BIOLOGY = SubjectCurriculum(
    subject=SubjectId.BIOLOGY,
    title="Biology",
    title_bn="জীববিজ্ঞান",
    icon="🧬",
    target_exams=[TargetExam.MEDICAL, TargetExam.DU, TargetExam.GST],
    units=[
        Unit(
            id="bio-cell",
            title="Cell Biology",
            title_bn="কোষ জীববিজ্ঞান",
            description="Cell structure, organelles, division, transport",
            description_bn="কোষ গঠন, অঙ্গাণু, বিভাজন, পরিবহন",
            icon="🔬",
            nctb_chapter="1-3",
            nctb_class="XI",
            order=1,
            lessons=[
                _lesson("bio-cell-01", "Cell Structure & Organelles", "কোষ গঠন ও অঙ্গাণু",
                        "Prokaryotic vs eukaryotic, organelle functions",
                        "প্রোক্যারিওটিক বনাম ইউক্যারিওটিক, অঙ্গাণুর কাজ",
                        Difficulty.EASY, 1, ["mitochondria", "ribosome"]),
                _lesson("bio-cell-02", "Cell Membrane & Transport", "কোষ ঝিল্লি ও পরিবহন",
                        "Osmosis, diffusion, active transport, endocytosis",
                        "অভিস্রবণ, ব্যাপন, সক্রিয় পরিবহন",
                        Difficulty.MEDIUM, 2, ["osmosis", "Na-K pump"]),
                _lesson("bio-cell-03", "Cell Division", "কোষ বিভাজন",
                        "Mitosis, meiosis, cell cycle, significance",
                        "মাইটোসিস, মিয়োসিস, কোষ চক্র, তাৎপর্য",
                        Difficulty.MEDIUM, 3, ["mitosis phases", "crossing over"]),
            ],
        ),
        Unit(
            id="bio-genetics",
            title="Genetics & Molecular Biology",
            title_bn="জিনতত্ত্ব ও আণবিক জীববিজ্ঞান",
            description="DNA, RNA, protein synthesis, Mendelian genetics",
            description_bn="DNA, RNA, প্রোটিন সংশ্লেষণ, মেন্ডেলের জিনতত্ত্ব",
            icon="🧬",
            nctb_chapter="4-6",
            nctb_class="XII",
            order=2,
            lessons=[
                _lesson("bio-gen-01", "DNA Structure & Replication", "DNA গঠন ও প্রতিলিপি",
                        "Double helix, base pairing, replication fork",
                        "দ্বিসূত্রক হেলিক্স, ক্ষারক জোড়, প্রতিলিপি কাটাচামচ",
                        Difficulty.MEDIUM, 1, ["A-T", "G-C"]),
                _lesson("bio-gen-02", "Transcription & Translation", "ট্রান্সক্রিপশন ও ট্রান্সলেশন",
                        "mRNA, tRNA, ribosome, codons, protein synthesis",
                        "mRNA, tRNA, রাইবোজোম, কোডন, প্রোটিন সংশ্লেষণ",
                        Difficulty.HARD, 2, ["central dogma", "codon table"]),
                _lesson("bio-gen-03", "Mendelian Genetics", "মেন্ডেলের জিনতত্ত্ব",
                        "Monohybrid, dihybrid, dominance, Punnett square",
                        "একসংকর, দ্বিসংকর, প্রকটতা, পানেট স্কোয়ার",
                        Difficulty.MEDIUM, 3, ["3:1 ratio", "Punnett"]),
                _lesson("bio-gen-04", "Genetic Disorders & Biotechnology", "জিনগত রোগ ও জৈবপ্রযুক্তি",
                        "Mutations, genetic engineering, PCR, cloning",
                        "মিউটেশন, জিনগত প্রকৌশল, PCR, ক্লোনিং",
                        Difficulty.HARD, 4, ["PCR", "gene therapy"]),
            ],
        ),
        Unit(
            id="bio-botany",
            title="Plant Biology",
            title_bn="উদ্ভিদবিজ্ঞান",
            description="Photosynthesis, respiration, transport, reproduction",
            description_bn="সালোকসংশ্লেষণ, শ্বসন, পরিবহন, প্রজনন",
            icon="🌿",
            nctb_chapter="7-9",
            nctb_class="XI",
            order=3,
            lessons=[
                _lesson("bio-bot-01", "Photosynthesis", "সালোকসংশ্লেষণ",
                        "Light & dark reactions, Calvin cycle, C3/C4 plants",
                        "আলোক ও অন্ধকার বিক্রিয়া, ক্যালভিন চক্র",
                        Difficulty.MEDIUM, 1, ["6CO₂+6H₂O→C₆H₁₂O₆+6O₂"]),
                _lesson("bio-bot-02", "Respiration", "শ্বসন",
                        "Glycolysis, Krebs cycle, ETC, ATP yield",
                        "গ্লাইকোলাইসিস, ক্রেবস চক্র, ETC, ATP উৎপাদন",
                        Difficulty.HARD, 2, ["glycolysis", "36-38 ATP"]),
                _lesson("bio-bot-03", "Plant Hormones & Movement", "উদ্ভিদ হরমোন ও চলন",
                        "Auxin, gibberellin, tropisms, nastic movements",
                        "অক্সিন, জিবারেলিন, ট্রপিজম, ন্যাস্টিক চলন",
                        Difficulty.EASY, 3, ["auxin", "phototropism"]),
            ],
        ),
        Unit(
            id="bio-zoology",
            title="Human Biology & Zoology",
            title_bn="মানবদেহ ও প্রাণিবিজ্ঞান",
            description="Physiology, systems, ecology, evolution",
            description_bn="শারীরবিদ্যা, তন্ত্র, বাস্তুবিদ্যা, বিবর্তন",
            icon="🫀",
            nctb_chapter="10-14",
            nctb_class="XI-XII",
            order=4,
            lessons=[
                _lesson("bio-zoo-01", "Circulatory System", "রক্ত সংবহন তন্ত্র",
                        "Heart, blood vessels, blood types, circulation",
                        "হৃৎপিণ্ড, রক্তনালী, রক্তের গ্রুপ, সংবহন",
                        Difficulty.MEDIUM, 1, ["ABO blood group", "cardiac cycle"]),
                _lesson("bio-zoo-02", "Nervous System", "স্নায়ুতন্ত্র",
                        "Neurons, synapses, brain, reflex arc",
                        "নিউরন, সাইন্যাপস, মস্তিষ্ক, প্রতিবর্ত ক্রিয়া",
                        Difficulty.MEDIUM, 2, ["action potential", "synapse"]),
                _lesson("bio-zoo-03", "Endocrine System", "অন্তঃক্ষরা তন্ত্র",
                        "Hormones, glands, feedback mechanisms",
                        "হরমোন, গ্রন্থি, ফিডব্যাক প্রক্রিয়া",
                        Difficulty.MEDIUM, 3, ["insulin", "thyroid"]),
                _lesson("bio-zoo-04", "Ecology & Environment", "বাস্তুবিদ্যা ও পরিবেশ",
                        "Ecosystem, food web, nitrogen cycle, biodiversity",
                        "বাস্তুতন্ত্র, খাদ্যজাল, নাইট্রোজেন চক্র, জীববৈচিত্র্য",
                        Difficulty.EASY, 4, ["food chain", "energy flow"]),
                _lesson("bio-zoo-05", "Evolution", "বিবর্তন",
                        "Natural selection, speciation, evidence of evolution",
                        "প্রাকৃতিক নির্বাচন, প্রজাতি সৃষ্টি, বিবর্তনের প্রমাণ",
                        Difficulty.MEDIUM, 5, ["Darwin", "natural selection"]),
            ],
        ),
    ],
)


# ── Registry ─────────────────────────────────────────────────────────────────

ALL_SUBJECTS: dict[SubjectId, SubjectCurriculum] = {
    SubjectId.PHYSICS: PHYSICS,
    SubjectId.CHEMISTRY: CHEMISTRY,
    SubjectId.HIGHER_MATH: HIGHER_MATH,
    SubjectId.GENERAL_MATH: GENERAL_MATH,
    SubjectId.BIOLOGY: BIOLOGY,
}

# Which subjects each exam cares about
EXAM_SUBJECTS: dict[TargetExam, list[SubjectId]] = {
    TargetExam.BUET: [SubjectId.PHYSICS, SubjectId.CHEMISTRY, SubjectId.HIGHER_MATH],
    TargetExam.MEDICAL: [SubjectId.BIOLOGY, SubjectId.CHEMISTRY, SubjectId.PHYSICS, SubjectId.GENERAL_MATH],
    TargetExam.DU: [SubjectId.PHYSICS, SubjectId.CHEMISTRY, SubjectId.HIGHER_MATH, SubjectId.GENERAL_MATH, SubjectId.BIOLOGY],
    TargetExam.GST: [SubjectId.PHYSICS, SubjectId.CHEMISTRY, SubjectId.HIGHER_MATH, SubjectId.BIOLOGY],
    TargetExam.GENERAL: [SubjectId.PHYSICS, SubjectId.CHEMISTRY, SubjectId.HIGHER_MATH, SubjectId.GENERAL_MATH, SubjectId.BIOLOGY],
}
